#!/usr/bin/env python3
"""
Test script for semantic layer (without LLM dependency)
Run this to verify semantic layer is working correctly
"""
from pathlib import Path
from semantic_layer.semantic_layer import SemanticLayer
from semantic_layer.models import QueryIntent


def test_semantic_layer():
    """Test semantic layer functionality"""

    print("="*70)
    print("Testing Semantic Layer")
    print("="*70)

    # Initialize semantic layer
    config_path = Path(__file__).parent / "semantic_layer" / "config.yaml"
    sl = SemanticLayer(str(config_path))

    print(f"\nLoaded {len(sl.metrics)} metrics")
    print(f"Loaded {len(sl.dimensions)} dimensions")

    # Test 1: Simple metric query
    print("\n" + "="*70)
    print("Test 1: Simple metric query")
    print("="*70)

    intent1 = QueryIntent(
        metrics=["total_transactions"],
        group_by=[],
        filters=[],
        time_period=None,
        limit=None,
        original_question="What is the total number of transactions?"
    )

    sql1 = sl.intent_to_sql(intent1)
    print(f"\nIntent: {intent1.original_question}")
    print(f"\nGenerated SQL:\n{sql1.sql}")
    print(f"\nExplanation: {sql1.explanation}")

    # Test 2: Metric with grouping
    print("\n" + "="*70)
    print("Test 2: Metric with grouping")
    print("="*70)

    intent2 = QueryIntent(
        metrics=["transaction_volume"],
        group_by=["month_name"],
        filters=[],
        time_period="d_date.year = 2024",
        limit=12,
        original_question="Show transaction volume by month in 2024"
    )

    sql2 = sl.intent_to_sql(intent2)
    print(f"\nIntent: {intent2.original_question}")
    print(f"\nGenerated SQL:\n{sql2.sql}")
    print(f"\nExplanation: {sql2.explanation}")

    # Test 3: Multiple metrics
    print("\n" + "="*70)
    print("Test 3: Multiple metrics")
    print("="*70)

    intent3 = QueryIntent(
        metrics=["total_deposits", "total_withdrawals"],
        group_by=["region"],
        filters=[],
        time_period=None,
        limit=None,
        original_question="Show deposits and withdrawals by region"
    )

    sql3 = sl.intent_to_sql(intent3)
    print(f"\nIntent: {intent3.original_question}")
    print(f"\nGenerated SQL:\n{sql3.sql}")
    print(f"\nExplanation: {sql3.explanation}")

    # Test 4: List available metrics
    print("\n" + "="*70)
    print("Test 4: Available Metrics")
    print("="*70)

    metrics = sl.list_available_metrics()
    for metric in metrics[:5]:  # Show first 5
        print(f"  - {metric['name']}: {metric['description']}")
    print(f"  ... and {len(metrics) - 5} more")

    # Test 5: List available dimensions
    print("\n" + "="*70)
    print("Test 5: Available Dimensions")
    print("="*70)

    dimensions = sl.list_available_dimensions()
    for dim in dimensions:
        attrs = ", ".join(dim['attributes'][:3])  # Show first 3 attributes
        print(f"  - {dim['name']}: {attrs}")

    print("\n" + "="*70)
    print("All tests completed successfully!")
    print("="*70)
    print("\nKey Insight: SQL is generated by semantic layer, NOT by LLM!")
    print("The LLM only maps user questions to semantic concepts.")
    print("="*70 + "\n")


if __name__ == '__main__':
    test_semantic_layer()
